[build-system]
requires = ["scikit-build-core>=0.3.3", "pybind11", "pybind11_stubgen", "cmake>=3.26", "netgen-mesher", "ngsolve"]
build-backend = "scikit_build_core.build"

[project]
name = "ngs_mumps"
version = "1.0.0"
description="A minimal example for an NGSolve addon"
readme = "README.md"
authors = [ { name = "NGSolve" } ]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
test = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.cibuildwheel]
skip = """
  pp*
  *_i686
  *musllinux*
  *win32
"""

[tool.cibuildwheel.linux]
repair-wheel-command = ""

[tool.cibuildwheel.macos]
environment = {MACOSX_DEPLOYMENT_TARGET=10.15}
repair-wheel-command = ""
archs = ["universal2"]
